// ESLint for the app.
//
// Added after a real crash rather than on principle. The tip-index useMemo in
// Guide.tsx sat below an `if (!g2) return <loading/>` guard, so it ran on some
// renders and not others, and opening the Guide screen died with "Rendered
// more hooks than during the previous render". tsc cannot see hook ordering,
// and the logic that useMemo fed was pure and already tested away from React
// — so its tests passed while the screen could not mount. rules-of-hooks is
// the check that closes that exact gap.
//
// WHAT IS AN ERROR AND WHY
//
// Only rules-of-hooks. It has no false positives worth the name, the codebase
// has zero violations of it today, and it is the one that already cost a
// crash. So it can gate a build honestly.
//
// Everything else is a warning, and that is a statement about review status
// rather than importance. eslint-plugin-react-hooks 7 ships the React
// Compiler rules — set-state-in-effect, refs, purity, static-components —
// which flag ~40 places here. None has been looked at. Turning them into
// errors would either block every commit or invite a blanket suppression, and
// a rule that gets suppressed teaches people to ignore the file. They stay
// visible as warnings until someone triages them properly; some are likely
// real, and setting-state-in-an-effect in particular is worth a pass.
//
// So: `eslint .` exits 0 today, and the day it exits 1 something genuinely
// broke the hook rules.

// defineConfig + eslint-config-expo/flat is the shape documented for SDK 54:
// https://docs.expo.dev/guides/using-eslint/
const { defineConfig } = require('eslint/config');
const expoConfig = require('eslint-config-expo/flat');
const ts = require('@typescript-eslint/eslint-plugin');

module.exports = defineConfig([
  expoConfig,
  {
    ignores: [
      'node_modules/**',
      'ios/**',        // generated by prebuild
      'android/**',    // generated by prebuild
      '.expo/**',
      'dist/**',
      'scripts/**',    // standalone checks, run by hand
    ],
  },
  {
    files: ['**/*.{js,jsx,ts,tsx}'],
    // Flat config requires a plugin to be declared in the same object that
    // sets one of its rules, even when an earlier object already declared it.
    plugins: { '@typescript-eslint': ts },
    rules: {
      // The rule this config exists for. Never downgrade it.
      'react-hooks/rules-of-hooks': 'error',

      // Frequently right, occasionally wrong — worth seeing, not worth blocking.
      'react-hooks/exhaustive-deps': 'warn',

      // React Compiler rules, new in plugin v7 and not yet triaged here.
      'react-hooks/set-state-in-effect': 'warn',
      'react-hooks/refs': 'warn',
      'react-hooks/purity': 'warn',
      'react-hooks/static-components': 'warn',

      // Style and hygiene. Real, but not defects.
      '@typescript-eslint/no-unused-vars': 'warn',
      'react/no-unescaped-entities': 'warn',
      'no-unused-expressions': 'warn',
    },
  },
]);
